---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-settings
  namespace: filebrowser
data:
  settings.json: |-
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/srv/filebrowser.db",
      "root": "/srv"
    }
